"""Generate src/weights.v from weights/{linear,mlp16,mlp32}.json.

Weights become Verilog localparam constants (bitmasks), so synthesis
constant-folds them into logic — no flip-flops or RAM are spent on storage.

Encoding per layer: two bitmasks per output unit.
  W1P_j bit i = 1  ->  weight(+1) from pixel i to unit j
  W1N_j bit i = 1  ->  weight(-1) from pixel i to unit j
  (both 0 -> weight 0)
Biases are 8-bit signed constants, flattened (unit j = bits [j*8 +: 8]).

All three variant modules expose identical (maximum-width) ports so the
core can instantiate any of them from a generate block; unused high bits
are constant zero and vanish at synthesis.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAXH = 32  # widest supported hidden layer


def masks(w_row):
    """Row of {-1,0,1} -> (pos_mask, neg_mask), bit i = input i."""
    pos = neg = 0
    for i, w in enumerate(w_row):
        if w == 1:
            pos |= 1 << i
        elif w == -1:
            neg |= 1 << i
        elif w != 0:
            raise ValueError(f"non-ternary weight {w}")
    return pos, neg


def bias_flat(biases, nbits):
    v = 0
    for j, b in enumerate(biases):
        v |= (b & 0xFF) << (8 * j)
    return v & ((1 << nbits) - 1)


def emit_layer(lines, prefix, weights, nbits):
    fmt = f"{{:0{(nbits + 3) // 4}x}}"
    for j, row in enumerate(weights):
        p, n = masks(row)
        lines.append(f"  localparam [{nbits-1}:0] {prefix}P_{j} = {nbits}'h{fmt.format(p)};")
        lines.append(f"  localparam [{nbits-1}:0] {prefix}N_{j} = {nbits}'h{fmt.format(n)};")


def concat_sel(prefix, suffix, n, idx, pad=0):
    """{pad'b0, PREFIX_{n-1}[idx], ..., PREFIX_0[idx]}"""
    terms = [f"{prefix}{suffix}_{j}[{idx}]" for j in range(n - 1, -1, -1)]
    padding = [f"{pad}'b0"] if pad else []
    return "{" + ",\n           ".join(padding + terms) + "}"


def gen_module(name, wts):
    is_mlp = "w2" in wts
    nh = len(wts["w1"])  # hidden units (MLP) or 10 (linear)
    lines = [f"module {name} ("]
    lines += [
        "    input  wire [5:0]   idx,     // pixel index (layer 1)",
        "    input  wire [4:0]   hidx,    // hidden index (layer 2, MLP only)",
        f"    output wire [{MAXH-1}:0]  l1_pos,",
        f"    output wire [{MAXH-1}:0]  l1_neg,",
        f"    output wire [{MAXH*8-1}:0] b1_flat, // unit j bias at [j*8 +: 8], signed",
        "    output wire [9:0]   l2_pos,",
        "    output wire [9:0]   l2_neg,",
        "    output wire [79:0]  b2_flat",
        ");",
    ]
    emit_layer(lines, "W1", wts["w1"], 64)
    b1 = bias_flat(wts["b1"], MAXH * 8)
    lines.append(f"  localparam [{MAXH*8-1}:0] B1 = {MAXH*8}'h{b1:0{MAXH*2}x};")
    if is_mlp:
        # pad each class's hidden-weight row to MAXH bits
        w2 = [row + [0] * (MAXH - nh) for row in wts["w2"]]
        emit_layer(lines, "W2", w2, MAXH)
        b2 = bias_flat(wts["b2"], 80)
        lines.append(f"  localparam [79:0] B2 = 80'h{b2:020x};")
    lines.append("")
    pad = MAXH - nh
    lines.append(f"  assign l1_pos = {concat_sel('W1', 'P', nh, 'idx', pad)};")
    lines.append(f"  assign l1_neg = {concat_sel('W1', 'N', nh, 'idx', pad)};")
    lines.append("  assign b1_flat = B1;")
    if is_mlp:
        lines.append(f"  assign l2_pos = {concat_sel('W2', 'P', 10, 'hidx')};")
        lines.append(f"  assign l2_neg = {concat_sel('W2', 'N', 10, 'hidx')};")
        lines.append("  assign b2_flat = B2;")
    else:
        lines.append("  assign l2_pos = 10'b0;")
        lines.append("  assign l2_neg = 10'b0;")
        lines.append("  assign b2_flat = 80'b0;")
        lines.append("  wire _unused = &{hidx, 1'b0};")
    lines.append("endmodule")
    return "\n".join(lines)


def main():
    mods, thresh = [], None
    for name in ("linear", "mlp16", "mlp32"):
        with open(os.path.join(ROOT, "weights", f"{name}.json")) as f:
            wts = json.load(f)
        thresh = wts["bin_threshold"]
        mods.append(gen_module(f"mnist_weights_{name}", wts))

    header = (
        "/*\n"
        " * AUTO-GENERATED by train/gen_weights.py — DO NOT EDIT.\n"
        " * Ternary MNIST weights as constants (constant-folded at synthesis).\n"
        f" * Binarization threshold: {thresh}\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " */\n\n`default_nettype none\n\n"
    )
    path = os.path.join(ROOT, "src", "weights.v")
    with open(path, "w") as f:
        f.write(header + "\n\n".join(mods) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
