/*
 * AUTO-GENERATED by train/gen_weights.py — DO NOT EDIT.
 * Ternary MNIST weights as constants (constant-folded at synthesis).
 * Binarization threshold: 0.15
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module mnist_weights_linear (
    input  wire [5:0]   idx,     // pixel index (layer 1)
    input  wire [4:0]   hidx,    // hidden index (layer 2, MLP only)
    output wire [31:0]  l1_pos,
    output wire [31:0]  l1_neg,
    output wire [255:0] b1_flat, // unit j bias at [j*8 +: 8], signed
    output wire [9:0]   l2_pos,
    output wire [9:0]   l2_neg,
    output wire [79:0]  b2_flat
);
  localparam [63:0] W1P_0 = 64'h000c24c644201000;
  localparam [63:0] W1N_0 = 64'h7e4111191186c67c;
  localparam [63:0] W1P_1 = 64'h0000081810100000;
  localparam [63:0] W1N_1 = 64'h3e4127e6eeee847c;
  localparam [63:0] W1P_2 = 64'h00e6fe8000001c08;
  localparam [63:0] W1N_2 = 64'h7e1800605f80c040;
  localparam [63:0] W1P_3 = 64'h0617232010120e00;
  localparam [63:0] W1N_3 = 64'h00c08c84c688c044;
  localparam [63:0] W1P_4 = 64'h0000103e24204000;
  localparam [63:0] W1N_4 = 64'h7e0ee780819a187c;
  localparam [63:0] W1P_5 = 64'h002c02000cc0e000;
  localparam [63:0] W1N_5 = 64'h060309566103027c;
  localparam [63:0] W1P_6 = 64'h00003c444800207c;
  localparam [63:0] W1N_6 = 64'h7ee6830131f70000;
  localparam [63:0] W1P_7 = 64'h1e000020233f0000;
  localparam [63:0] W1N_7 = 64'h0075e68c8880f83c;
  localparam [63:0] W1P_8 = 64'h10380c08c8443000;
  localparam [63:0] W1N_8 = 64'h428113e70110027c;
  localparam [63:0] W1P_9 = 64'h7e00002d26180000;
  localparam [63:0] W1N_9 = 64'h001eeec081c3ee7c;
  localparam [255:0] B1 = 256'h0000000000000000000000000000000000000000000000fe01000100ff0002ff;

  assign l1_pos = {22'b0,
           W1P_9[idx],
           W1P_8[idx],
           W1P_7[idx],
           W1P_6[idx],
           W1P_5[idx],
           W1P_4[idx],
           W1P_3[idx],
           W1P_2[idx],
           W1P_1[idx],
           W1P_0[idx]};
  assign l1_neg = {22'b0,
           W1N_9[idx],
           W1N_8[idx],
           W1N_7[idx],
           W1N_6[idx],
           W1N_5[idx],
           W1N_4[idx],
           W1N_3[idx],
           W1N_2[idx],
           W1N_1[idx],
           W1N_0[idx]};
  assign b1_flat = B1;
  assign l2_pos = 10'b0;
  assign l2_neg = 10'b0;
  assign b2_flat = 80'b0;
  wire _unused = &{hidx, 1'b0};
endmodule

module mnist_weights_mlp16 (
    input  wire [5:0]   idx,     // pixel index (layer 1)
    input  wire [4:0]   hidx,    // hidden index (layer 2, MLP only)
    output wire [31:0]  l1_pos,
    output wire [31:0]  l1_neg,
    output wire [255:0] b1_flat, // unit j bias at [j*8 +: 8], signed
    output wire [9:0]   l2_pos,
    output wire [9:0]   l2_neg,
    output wire [79:0]  b2_flat
);
  localparam [63:0] W1P_0 = 64'h60c0c89a000010fc;
  localparam [63:0] W1N_0 = 64'h0e1800401ee38000;
  localparam [63:0] W1P_1 = 64'h000824e646090076;
  localparam [63:0] W1N_1 = 64'h60e5831910e0da00;
  localparam [63:0] W1P_2 = 64'h7e0102270fb00000;
  localparam [63:0] W1N_2 = 64'h00008c18c00fe47c;
  localparam [63:0] W1P_3 = 64'h0053edcc6020160c;
  localparam [63:0] W1N_3 = 64'h4204000019910000;
  localparam [63:0] W1P_4 = 64'h72c0803104ec8000;
  localparam [63:0] W1N_4 = 64'h001f25c0d0003a7e;
  localparam [63:0] W1P_5 = 64'h7600011131130200;
  localparam [63:0] W1N_5 = 64'h004ce604c8c0607c;
  localparam [63:0] W1P_6 = 64'h1e2f21091880c260;
  localparam [63:0] W1N_6 = 64'h00c09c86e165000c;
  localparam [63:0] W1P_7 = 64'h78100800c3f80000;
  localparam [63:0] W1N_7 = 64'h0641732c20008e7c;
  localparam [63:0] W1P_8 = 64'h6008000ccc88f04e;
  localparam [63:0] W1N_8 = 64'h0287839311330e00;
  localparam [63:0] W1P_9 = 64'h001000580cc0e440;
  localparam [63:0] W1N_9 = 64'h7e06c30161381000;
  localparam [63:0] W1P_10 = 64'h181f2700a1f71e00;
  localparam [63:0] W1N_10 = 64'h408010de1600007c;
  localparam [63:0] W1P_11 = 64'h068fe3a1018f8600;
  localparam [63:0] W1N_11 = 64'h00000c1efc001040;
  localparam [63:0] W1P_12 = 64'h007ec91888c0c87c;
  localparam [63:0] W1N_12 = 64'h4600106764380200;
  localparam [63:0] W1P_13 = 64'h0e01003b31230000;
  localparam [63:0] W1N_13 = 64'h20ccf6c088d0187e;
  localparam [63:0] W1P_14 = 64'h00e0d0c404a06000;
  localparam [63:0] W1N_14 = 64'h7e0a01113b160a60;
  localparam [63:0] W1P_15 = 64'h000363d010030efc;
  localparam [63:0] W1N_15 = 64'h7c7800026eecc000;
  localparam [255:0] B1 = 256'h000000000000000000000000000000000101000001fe00ff00ff0000fd000000;
  localparam [31:0] W2P_0 = 32'h0000440a;
  localparam [31:0] W2N_0 = 32'h0000b271;
  localparam [31:0] W2P_1 = 32'h000090a0;
  localparam [31:0] W2N_1 = 32'h00000d1e;
  localparam [31:0] W2P_2 = 32'h0000cc09;
  localparam [31:0] W2N_2 = 32'h000023c6;
  localparam [31:0] W2P_3 = 32'h00008c44;
  localparam [31:0] W2N_3 = 32'h00004193;
  localparam [31:0] W2P_4 = 32'h00002230;
  localparam [31:0] W2N_4 = 32'h00001cc0;
  localparam [31:0] W2P_5 = 32'h00001a50;
  localparam [31:0] W2N_5 = 32'h0000202b;
  localparam [31:0] W2P_6 = 32'h00008303;
  localparam [31:0] W2N_6 = 32'h00002cb4;
  localparam [31:0] W2P_7 = 32'h00002832;
  localparam [31:0] W2N_7 = 32'h00005349;
  localparam [31:0] W2P_8 = 32'h00001580;
  localparam [31:0] W2N_8 = 32'h0000c807;
  localparam [31:0] W2P_9 = 32'h00002135;
  localparam [31:0] W2N_9 = 32'h0000de00;
  localparam [79:0] B2 = 80'h00000000000000000000;

  assign l1_pos = {16'b0,
           W1P_15[idx],
           W1P_14[idx],
           W1P_13[idx],
           W1P_12[idx],
           W1P_11[idx],
           W1P_10[idx],
           W1P_9[idx],
           W1P_8[idx],
           W1P_7[idx],
           W1P_6[idx],
           W1P_5[idx],
           W1P_4[idx],
           W1P_3[idx],
           W1P_2[idx],
           W1P_1[idx],
           W1P_0[idx]};
  assign l1_neg = {16'b0,
           W1N_15[idx],
           W1N_14[idx],
           W1N_13[idx],
           W1N_12[idx],
           W1N_11[idx],
           W1N_10[idx],
           W1N_9[idx],
           W1N_8[idx],
           W1N_7[idx],
           W1N_6[idx],
           W1N_5[idx],
           W1N_4[idx],
           W1N_3[idx],
           W1N_2[idx],
           W1N_1[idx],
           W1N_0[idx]};
  assign b1_flat = B1;
  assign l2_pos = {W2P_9[hidx],
           W2P_8[hidx],
           W2P_7[hidx],
           W2P_6[hidx],
           W2P_5[hidx],
           W2P_4[hidx],
           W2P_3[hidx],
           W2P_2[hidx],
           W2P_1[hidx],
           W2P_0[hidx]};
  assign l2_neg = {W2N_9[hidx],
           W2N_8[hidx],
           W2N_7[hidx],
           W2N_6[hidx],
           W2N_5[hidx],
           W2N_4[hidx],
           W2N_3[hidx],
           W2N_2[hidx],
           W2N_1[hidx],
           W2N_0[hidx]};
  assign b2_flat = B2;
endmodule

module mnist_weights_mlp32 (
    input  wire [5:0]   idx,     // pixel index (layer 1)
    input  wire [4:0]   hidx,    // hidden index (layer 2, MLP only)
    output wire [31:0]  l1_pos,
    output wire [31:0]  l1_neg,
    output wire [255:0] b1_flat, // unit j bias at [j*8 +: 8], signed
    output wire [9:0]   l2_pos,
    output wire [9:0]   l2_neg,
    output wire [79:0]  b2_flat
);
  localparam [63:0] W1P_0 = 64'h000018780001c67c;
  localparam [63:0] W1N_0 = 64'h7e5200010ff80000;
  localparam [63:0] W1P_1 = 64'h0800408091110200;
  localparam [63:0] W1N_1 = 64'h4002080660c07070;
  localparam [63:0] W1P_2 = 64'h6860000304083060;
  localparam [63:0] W1N_2 = 64'h000e66c091e38e00;
  localparam [63:0] W1P_3 = 64'h0010001c1c80c000;
  localparam [63:0] W1N_3 = 64'h30828f818138003c;
  localparam [63:0] W1P_4 = 64'h18fe220000ef1c04;
  localparam [63:0] W1N_4 = 64'h420001ff5c000040;
  localparam [63:0] W1P_5 = 64'h02000033242b4000;
  localparam [63:0] W1N_5 = 64'h088fe60888c0187e;
  localparam [63:0] W1P_6 = 64'h4e010111311b061c;
  localparam [63:0] W1N_6 = 64'h00f04e888ce0f020;
  localparam [63:0] W1P_7 = 64'h1800100088d84000;
  localparam [63:0] W1N_7 = 64'h02e1e1e767071e3c;
  localparam [63:0] W1P_8 = 64'h00f7c70000f03800;
  localparam [63:0] W1N_8 = 64'h06000870e60c0060;
  localparam [63:0] W1P_9 = 64'h00100c90c3074014;
  localparam [63:0] W1N_9 = 64'h42c173260c200020;
  localparam [63:0] W1P_10 = 64'h00c7031120203e08;
  localparam [63:0] W1N_10 = 64'h020020e48e9cc040;
  localparam [63:0] W1P_11 = 64'h0001711c2000125c;
  localparam [63:0] W1N_11 = 64'h108080000cccc000;
  localparam [63:0] W1P_12 = 64'h00607c8cc400804c;
  localparam [63:0] W1N_12 = 64'h5e06012119100000;
  localparam [63:0] W1P_13 = 64'h0040548c46088004;
  localparam [63:0] W1N_13 = 64'h0200011031d30e20;
  localparam [63:0] W1P_14 = 64'h4000000080f20200;
  localparam [63:0] W1N_14 = 64'h1e4375e160083c58;
  localparam [63:0] W1P_15 = 64'h7e010229becc8000;
  localparam [63:0] W1N_15 = 64'h002008c64001007c;
  localparam [63:0] W1P_16 = 64'h601820440608007c;
  localparam [63:0] W1N_16 = 64'h0201431830670800;
  localparam [63:0] W1P_17 = 64'h30000c18e008104c;
  localparam [63:0] W1N_17 = 64'h0287e36201f30600;
  localparam [63:0] W1P_18 = 64'h4601012701300200;
  localparam [63:0] W1N_18 = 64'h001ccc80c800d06e;
  localparam [63:0] W1P_19 = 64'h1e400139216f0000;
  localparam [63:0] W1N_19 = 64'h000c6e80d8001a7e;
  localparam [63:0] W1P_20 = 64'h7e420600c0781800;
  localparam [63:0] W1N_20 = 64'h000001521881627c;
  localparam [63:0] W1P_21 = 64'h00f4c01898c44000;
  localparam [63:0] W1N_21 = 64'h0600336721310278;
  localparam [63:0] W1P_22 = 64'h0e1f61e00800f200;
  localparam [63:0] W1N_22 = 64'h20801c1af0600004;
  localparam [63:0] W1P_23 = 64'h261923001900007c;
  localparam [63:0] W1N_23 = 64'h40c08486a2e00000;
  localparam [63:0] W1P_24 = 64'h006173089880867c;
  localparam [63:0] W1N_24 = 64'h7e00000366381000;
  localparam [63:0] W1P_25 = 64'h00007ce00103007c;
  localparam [63:0] W1N_25 = 64'h6c710118b000f800;
  localparam [63:0] W1P_26 = 64'h0007850600303a00;
  localparam [63:0] W1N_26 = 64'h722010111f8ec060;
  localparam [63:0] W1P_27 = 64'h1e1a0400cb330000;
  localparam [63:0] W1N_27 = 64'h40e0d01e00004474;
  localparam [63:0] W1P_28 = 64'h00e000060ee8c000;
  localparam [63:0] W1N_28 = 64'h0603390001120e7c;
  localparam [63:0] W1P_29 = 64'h3c08002ccec8c040;
  localparam [63:0] W1N_29 = 64'h00874b000010081c;
  localparam [63:0] W1P_30 = 64'h7e82c910017d0000;
  localparam [63:0] W1N_30 = 64'h000830664c00e430;
  localparam [63:0] W1P_31 = 64'h60c4e3000008c81c;
  localparam [63:0] W1N_31 = 64'h00180806f0230200;
  localparam [255:0] B1 = 256'h0100ff00ffff0100ffff00fe0001ff00fe02ffffffff0000010100ffff010001;
  localparam [31:0] W2P_0 = 32'h1e512100;
  localparam [31:0] W2N_0 = 32'hc1ac464f;
  localparam [31:0] W2P_1 = 32'h40204786;
  localparam [31:0] W2N_1 = 32'h2a58b030;
  localparam [31:0] W2P_2 = 32'hc7001513;
  localparam [31:0] W2N_2 = 32'h38c5c088;
  localparam [31:0] W2P_3 = 32'h09c40d02;
  localparam [31:0] W2N_3 = 32'h100372a4;
  localparam [31:0] W2P_4 = 32'h300c0029;
  localparam [31:0] W2N_4 = 32'hced10710;
  localparam [31:0] W2P_5 = 32'h9061c080;
  localparam [31:0] W2N_5 = 32'h04022e62;
  localparam [31:0] W2P_6 = 32'h03831805;
  localparam [31:0] W2N_6 = 32'h5c1c8532;
  localparam [31:0] W2P_7 = 32'h4a1c0262;
  localparam [31:0] W2N_7 = 32'h81623908;
  localparam [31:0] W2P_8 = 32'h20228210;
  localparam [31:0] W2N_8 = 32'h82054040;
  localparam [31:0] W2P_9 = 32'h40162864;
  localparam [31:0] W2N_9 = 32'h07614311;
  localparam [79:0] B2 = 80'h00ff0000000000000000;

  assign l1_pos = {W1P_31[idx],
           W1P_30[idx],
           W1P_29[idx],
           W1P_28[idx],
           W1P_27[idx],
           W1P_26[idx],
           W1P_25[idx],
           W1P_24[idx],
           W1P_23[idx],
           W1P_22[idx],
           W1P_21[idx],
           W1P_20[idx],
           W1P_19[idx],
           W1P_18[idx],
           W1P_17[idx],
           W1P_16[idx],
           W1P_15[idx],
           W1P_14[idx],
           W1P_13[idx],
           W1P_12[idx],
           W1P_11[idx],
           W1P_10[idx],
           W1P_9[idx],
           W1P_8[idx],
           W1P_7[idx],
           W1P_6[idx],
           W1P_5[idx],
           W1P_4[idx],
           W1P_3[idx],
           W1P_2[idx],
           W1P_1[idx],
           W1P_0[idx]};
  assign l1_neg = {W1N_31[idx],
           W1N_30[idx],
           W1N_29[idx],
           W1N_28[idx],
           W1N_27[idx],
           W1N_26[idx],
           W1N_25[idx],
           W1N_24[idx],
           W1N_23[idx],
           W1N_22[idx],
           W1N_21[idx],
           W1N_20[idx],
           W1N_19[idx],
           W1N_18[idx],
           W1N_17[idx],
           W1N_16[idx],
           W1N_15[idx],
           W1N_14[idx],
           W1N_13[idx],
           W1N_12[idx],
           W1N_11[idx],
           W1N_10[idx],
           W1N_9[idx],
           W1N_8[idx],
           W1N_7[idx],
           W1N_6[idx],
           W1N_5[idx],
           W1N_4[idx],
           W1N_3[idx],
           W1N_2[idx],
           W1N_1[idx],
           W1N_0[idx]};
  assign b1_flat = B1;
  assign l2_pos = {W2P_9[hidx],
           W2P_8[hidx],
           W2P_7[hidx],
           W2P_6[hidx],
           W2P_5[hidx],
           W2P_4[hidx],
           W2P_3[hidx],
           W2P_2[hidx],
           W2P_1[hidx],
           W2P_0[hidx]};
  assign l2_neg = {W2N_9[hidx],
           W2N_8[hidx],
           W2N_7[hidx],
           W2N_6[hidx],
           W2N_5[hidx],
           W2N_4[hidx],
           W2N_3[hidx],
           W2N_2[hidx],
           W2N_1[hidx],
           W2N_0[hidx]};
  assign b2_flat = B2;
endmodule
